AWSTemplateFormatVersion: '2010-09-09'
Description: '

  Sample SAM Template for s3-lambda-s3 function

  '
Globals:
  Function:
    Timeout: 120
Outputs:
  InputS3Bucket:
    Description: Input Bucket name
    Value:
      Ref: InputS3Bucket
  LambdaFunctionARN:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CopyFileLambdaFunction
      - Arn
  LambdaFunctionRole:
    Description: Implicit IAM Role created for the lambda function
    Value:
      Fn::GetAtt:
      - CopyFileLambdaFunctionRole
      - Arn
  OutputS3Bucket:
    Description: Output Bucket name
    Value:
      Ref: OutputS3Bucket
Parameters:
  InputS3BucketName:
    Default: s3-lambda-copy-input-bucket-daghan
    MinLength: 3
    Type: String
  OutputS3BucketName:
    Default: s3-lambda-copy-output-bucket-daghan
    MinLength: 3
    Type: String
Resources:
  CopyFileLambdaFunction:
    Properties:
      CodeUri: s3://my-test-bucket-for-sam-template/38609677e8c3a50bb9380c2e68197e4d
      Environment:
        Variables:
          OUTPUT_BUCKET:
            Ref: OutputS3Bucket
      Events:
        FileUploadTrigger:
          Properties:
            Bucket:
              Ref: InputS3Bucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: app.lambdaHandler
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: OutputS3BucketName
      - S3ReadPolicy:
          BucketName:
            Ref: InputS3BucketName
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  InputS3Bucket:
    Properties:
      BucketName:
        Ref: InputS3BucketName
    Type: AWS::S3::Bucket
  OutputS3Bucket:
    Properties:
      BucketName:
        Ref: OutputS3BucketName
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
