AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  COIN

  Sample SAM Template for COIN
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Parameters:
  InputS3BucketName:
    Default: s3-lambda-transcribe-input-audio-bucket
    MinLength: 3
    Type: String
  OutputS3BucketName:
    Default: s3-lambda-transcribe-output-text-bucket
    MinLength: 3
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        FileUploadTrigger:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties: 
            Bucket: !Ref InputS3Bucket
            Events: s3:ObjectCreated:*
      Policies:
# We need to add bucket read and write policy permission to lambda function
      - S3CrudPolicy:
          BucketName: !Ref: OutputS3BucketName
# Create input and output buckets
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: InputS3BucketName
    
  OutputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: OutputS3BucketName
    

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionRole:
    Description: "Implicit IAM Role created for the lambda function"
    Value: !GetAtt LambdaFunctionRole.Arn
  InputS3Bucket:
    Description: "Input Bucket name"
    Value: !Ref InputS3Bucket
  OutputS3Bucket:
    Description: "Output Bucket name"
    Value: !Ref OutputS3Bucket

